name: data
on:
  # schedule:
    # - cron: 0/10 8-18 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./process-companies-data.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://docs.google.com/spreadsheets/u/0/d/1O-lVLR-QVykZ-cq7PlpLzjZGNpEcWaoq5b-ZnGpZWR0/export?format=csv&id=1O-lVLR-QVykZ-cq7PlpLzjZGNpEcWaoq5b-ZnGpZWR0&gid=0
          downloaded_filename: organisation-taxonomy.csv
          postprocess: ./process-companies-data.ts
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://docs.google.com/spreadsheets/d/1O-lVLR-QVykZ-cq7PlpLzjZGNpEcWaoq5b-ZnGpZWR0/export?format=csv&id=1O-lVLR-QVykZ-cq7PlpLzjZGNpEcWaoq5b-ZnGpZWR0&gid=13868823
          downloaded_filename: organisation-register.csv
          postprocess: ./process-companies-data.ts
